/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthGuard: typeof import('./src/components/AuthGuard.vue')['default']
    InputArea: typeof import('./src/components/InputArea.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    NotificationContainer: typeof import('./src/components/ui/NotificationContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionDetail: typeof import('./src/components/SessionDetail.vue')['default']
    SessionList: typeof import('./src/components/SessionList.vue')['default']
    StreamingMessage: typeof import('./src/components/StreamingMessage.vue')['default']
    ThinkingDisplay: typeof import('./src/components/ThinkingDisplay.vue')['default']
    ThinkingStep: typeof import('./src/components/ThinkingStep.vue')['default']
    TypewriterText: typeof import('./src/components/TypewriterText.vue')['default']
  }
}
